version: "3"

services:
  jupyter:
    build: .
    volumes:
      - .:/workarea
    ports:
      - 8888:8888
    user: root
    command: 
      /bin/bash -c \ 
      "jupyter lab --allow-root --ip=0.0.0.0"
